telegram:
  bot_token: ""

database:
  dsn: "postgres://realty_parser:password@realty-postgres:5432/realty_parser?sslmode=disable"

logging:
  level: "info"
  file_path: "/var/log/subscription-handler/app.log"

metrics:
  port: 9094
