package metro

import "testing"

// TestTopStationsDefaultMatchesReference checks that the unweighted ranking
// (no priority stations) matches the top-10 order already recorded in
// realty-parser's scoring.subways, which was generated by the same
// reference algorithm this package ports.
func TestTopStationsDefaultMatchesReference(t *testing.T) {
	want := []string{
		"Пушкинская", "Театральная", "Чеховская", "Тверская", "Кузнецкий Мост",
		"Третьяковская", "Арбатская", "Китай-город", "Боровицкая", "Площадь Революции",
	}
	got := TopStations(nil, 10)
	if len(got) != len(want) {
		t.Fatalf("expected %d results, got %d", len(want), len(got))
	}
	for i, name := range want {
		if got[i].Name != name {
			t.Errorf("position %d: expected %q, got %q", i+1, name, got[i].Name)
		}
	}
}

func TestMatchStationNamesCaseAndYo(t *testing.T) {
	matched, unmatched := MatchStationNames([]string{"щёлковская", "БЕЛОРУССКАЯ", "не станция"})
	if len(matched) != 2 || matched[0] != "Щёлковская" || matched[1] != "Белорусская" {
		t.Fatalf("unexpected matched: %v", matched)
	}
	if len(unmatched) != 1 || unmatched[0] != "не станция" {
		t.Fatalf("unexpected unmatched: %v", unmatched)
	}
}

func TestMatchStationNamesFirstOccurrenceOnly(t *testing.T) {
	idx := firstIndexByNormalizedName()
	i, ok := idx[normalizeStationName("Белорусская")]
	if !ok || i != 34 {
		t.Fatalf("expected first Белорусская occurrence at index 34, got %d (ok=%v)", i, ok)
	}
}

func TestTopStationsBoostsPriorityNeighborhood(t *testing.T) {
	baseline := TopStations(nil, 1)[0].Name
	boosted := TopStations([]string{"Щёлковская"}, 1)[0].Name
	if boosted == baseline {
		t.Fatalf("expected priority station to change the top result, still %q", baseline)
	}
}
